### ISSUE TITLE
v0.1 Features

### ISSUE THREAD

**Issue by mutetext** [kmangutov/janule#1]
**Feature ideas:**

1. Storage of meme -> meme, user -> meme, meme-> user relationships; meme; originator(s); date (See #12)
2. Add/remove meme (See #12, #13)
3. Add/remove relationship (See #14, #15)
4. Graph visualizations (universe, user(s) -> memes, meme(s) -> users, etc) (See #17)
5. Discord-friendly text (bot text should be one message) (See #4)
6. ML model to predict new memes (See #18)
7. Bot to scan all chat messages, ML model to determine if a new meme is contained, and notify users of likely new meme (See #19)
8. !memehelp (See #20)
9. Hosting (See #21)
10. Graph database (See #22)
11. Bot to scan all chat messages and archive them in .txt (Skipping this for now)
12. Autogenerate meme graphs using the entire text chat as a corpus. An example heuristic is, "link two phrases if they appear within 10 messages of each other twice in one day". (See #19)
13. Frequency counter for meme posting and association to user (to show impact of meme on users and meme popularity) (See #12)
14. CI/CD (See #10)
15. Frontend functionality (See #5)

**Comment by floethewarrior** [comment]
Joining

**Comment by bobchen1701** [comment]
fafnir

**Comment by bobchen1701** [comment]
re #6, look at https://github.com/BorisNikulin/discord-chat-analysis for scraping and tokenization, 
https://github.com/graphql-python/graphene with graphql opens up all the sklearn, networkx, igraph, and graph-tool for manual analysis

**Comment by mutetext** [comment]
Initial tickets created. Further discussion can be done on appropriate ticket/new tickets
